/* Labels for the React shell; content nodes remain owned by the UI bridge. */
(()=>{
 const copy={
 zh:{help:'帮助',restore:'返回对话','ed-name':'名字','ed-greeting':'开场白','ed-persona':'人设','ed-rate':'立绘动画速度','memory-title':'记忆','artifacts-title':'手记','artifacts-hint':'她写给你的文件都在这里。文件本身留在原处，这里只是翻开来看。','artifacts-empty':'还没有写过什么。','artifacts-back':'← 返回列表','artifacts-reveal':'在 Finder 中显示','artifacts-copy':'复制路径','artifacts-forget':'从列表移除','artifacts-presented':'已交付','artifacts-binary':'这种文件没法在这里打开，用「在 Finder 中显示」找到它。','artifacts-missing':'文件已经不在原来的位置了。','artifacts-revealed':'已在 Finder 中显示。','artifacts-copied':'路径已复制。','artifacts-got':'获得：','artifacts-kind-markdown':'Markdown','artifacts-kind-text':'文本','artifacts-kind-image':'图片','artifacts-kind-file':'文件','artifacts-missing-short':'已丢失','key-artifacts':'手记（她写的文件）','help-commands':'命令','help-keys-title':'快捷键','key-advance':'下一条 / 回到最新','key-input':'回到输入框','key-blur':'离开输入框（之后单键快捷键生效）','key-log':'对话记录','key-memory':'记忆','key-char':'切换角色','key-gallery':'立绘素材','key-edit':'角色设定','key-settings':'语音设置','key-voice':'开关自动朗读','key-replay':'重读本段','key-new':'开始新会话','key-hide':'隐藏界面','key-help':'打开帮助','memory-hint':'这些是关于你的笔记，所有角色共用，换角色也不会丢。','memory-empty':'还没有记住任何事。','memory-add':'记住一件事…','memory-add-button':'添加','memory-delete':'忘掉这条',save:'保存修改',import:'导入角色',export:'导出角色',galleryHint:'选择一张立绘预览表情。拖入图片或视频，或点击右上角上传按钮，即可替换素材。',history:'对话记录',close:'关闭',state:'状态预览'},
 en:{help:'Help',restore:'Back to dialogue','ed-name':'Name','ed-greeting':'Greeting','ed-persona':'Persona','ed-rate':'Artwork animation speed','memory-title':'Memory','artifacts-title':'Files','artifacts-hint':'Every file she wrote for you. The file stays where it is; this is just a way to open it.','artifacts-empty':'Nothing written yet.','artifacts-back':'← Back to list','artifacts-reveal':'Reveal in Finder','artifacts-copy':'Copy path','artifacts-forget':'Remove from list','artifacts-presented':'delivered','artifacts-binary':'This kind of file cannot be shown here. Use "Reveal in Finder" to find it.','artifacts-missing':'The file is no longer where it was.','artifacts-revealed':'Shown in Finder.','artifacts-copied':'Path copied.','artifacts-got':'Got: ','artifacts-kind-markdown':'Markdown','artifacts-kind-text':'Text','artifacts-kind-image':'Image','artifacts-kind-file':'File','artifacts-missing-short':'missing','key-artifacts':'Files she wrote','help-commands':'Commands','help-keys-title':'Keyboard','key-advance':'Next message / jump to latest','key-input':'Jump to the input box','key-blur':'Leave the input box (single keys work again)','key-log':'Conversation history','key-memory':'Memory','key-char':'Switch character','key-gallery':'Artwork','key-edit':'Persona','key-settings':'Speech settings','key-voice':'Auto voice on / off','key-replay':'Replay this line','key-new':'Start a new session','key-hide':'Hide the interface','key-help':'Open help','memory-hint':'Notes about you. Every character shares them, and they survive switching packs.','memory-empty':'Nothing remembered yet.','memory-add':'Remember something…','memory-add-button':'Add','memory-delete':'Forget this',save:'Save changes',import:'Import character',export:'Export character',galleryHint:'Select artwork to preview its expression. Drop an image or video, or use the upload button to replace it.',history:'Conversation history',close:'Close',state:'Stage preview'},
 ja:{help:'ヘルプ',restore:'会話に戻る','ed-name':'名前','ed-greeting':'あいさつ','ed-persona':'人格','ed-rate':'立ち絵の再生速度','memory-title':'記憶','artifacts-title':'手記','artifacts-hint':'彼女が書いたファイルの一覧。ファイル自体は元の場所にあり、ここでは開いて読むだけです。','artifacts-empty':'まだ何も書いていません。','artifacts-back':'← 一覧へ','artifacts-reveal':'Finder で表示','artifacts-copy':'パスをコピー','artifacts-forget':'一覧から外す','artifacts-presented':'納品済み','artifacts-binary':'この種類のファイルはここでは開けません。「Finder で表示」で探してください。','artifacts-missing':'ファイルは元の場所にありません。','artifacts-revealed':'Finder で表示しました。','artifacts-copied':'パスをコピーしました。','artifacts-got':'入手：','artifacts-kind-markdown':'Markdown','artifacts-kind-text':'テキスト','artifacts-kind-image':'画像','artifacts-kind-file':'ファイル','artifacts-missing-short':'見つかりません','key-artifacts':'手記（書いたファイル）','help-commands':'コマンド','help-keys-title':'ショートカット','key-advance':'次のメッセージ / 最新へ','key-input':'入力欄へ','key-blur':'入力欄から抜ける（単キー操作が有効に）','key-log':'会話履歴','key-memory':'記憶','key-char':'キャラ切替','key-gallery':'立ち絵素材','key-edit':'人格設定','key-settings':'音声設定','key-voice':'自動音声の切替','key-replay':'このセリフを再生','key-new':'新しい会話','key-hide':'画面を隠す','key-help':'ヘルプ','memory-hint':'あなたについてのメモ。全キャラクター共通で、切り替えても残ります。','memory-empty':'まだ何も覚えていません。','memory-add':'覚えておくことを入力…','memory-add-button':'追加','memory-delete':'この項目を忘れる',save:'変更を保存',import:'キャラを読み込む',export:'キャラを書き出す',galleryHint:'立ち絵を選んで表情を確認できます。画像や動画をドロップするか、アップロードボタンで素材を変更します。',history:'会話履歴',close:'閉じる',state:'状態プレビュー'}
 };
 function render(){const c=copy[window.galVoice.language]||copy.en;document.getElementById('character-state-preview').setAttribute('aria-label',c.state);document.querySelectorAll('[data-ui-text]').forEach(el=>el.textContent=c[el.dataset.uiText]||'');document.querySelectorAll('[data-ui-placeholder]').forEach(el=>el.placeholder=c[el.dataset.uiPlaceholder]||'');window.galLabels=c;}
 window.addEventListener('gal-language',render);render();
})();
